// spec -> standalone typed client. no deps, no browser
//   npm run synth -- films

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Field, Spec } from "../types.js";
import { toTs } from "../analyze/schema.js";
import { emit } from "../events.js";

const flowName = process.argv[2];
if (!flowName) {
  console.error("usage: npm run synth -- <flow name>");
  process.exit(1);
}

const spec: Spec = JSON.parse(
  await readFile(join("out", `${flowName}.spec.json`), "utf8"),
);

const name = pascal(spec.flow);

// two shapes of client: one that calls an endpoint, one that fetches the page
// and pulls the data out of it
if (spec.mode === "html") {
  await writeHtmlClient(spec, name);
  process.exit(0);
}
const params = [...new Set(spec.fields.filter(isParam).map((f) => f.boundTo!))];

const code = `// generated by beeline from ${spec.meta.runs} recorded runs.
// ${spec.target.method} ${spec.target.urlTemplate}
// ${spec.meta.generatedAt}
//
// do not edit: re-run \`npm run synth -- ${spec.flow}\` instead

export type ${name}Response = ${toTs(spec.responseSchema)};

export interface ${name}Params {
${params.map((p) => {
  const f = spec.fields.find((x) => x.boundTo === p);
  return `  ${p}${f?.optional ? "?" : ""}: string;${f?.note ? "  // " + f.note : ""}`;
}).join("\n")}
}

export class ${name}Client {
  private session: Record<string, string> = {};
  private cookies: Record<string, string> = {};
${bootstrapMethod(spec)}
  async call(params: ${name}Params): Promise<${name}Response> {
${guard(spec)}
    const url = new URL(${JSON.stringify(spec.target.urlTemplate)});
${queryLines(spec)}
    const res = await fetch(url, {
      method: ${JSON.stringify(spec.target.method)},
      headers: {
${headerLines(spec)}
      },${bodyLine(spec)}
    });

    if (!res.ok) {
      throw new Error(\`${spec.flow}: \${res.status} \${res.statusText}\`);
    }

    return ${readResponse(spec)} as ${name}Response;
  }

  private cookieHeader(): string {
    return Object.entries(this.cookies)
      .map(([k, v]) => \`\${k}=\${v}\`)
      .join("; ");
  }
}
`;

const outPath = join("out", `${spec.flow}.client.ts`);
await writeFile(outPath, code);

const unresolved = spec.unresolved.length;
console.log(`\n  wrote ${outPath}`);
console.log(
  `  ${params.length} param(s) · ${spec.bootstrap.length} bootstrap step(s)` +
    (unresolved ? ` · \x1b[31m${unresolved} field(s) hardcoded from capture\x1b[0m` : ""),
);
const lineCount = code.split("\n").length;
console.log(`  ${lineCount} lines\n`);
emit({ type: "client", flow: spec.flow, lines: lineCount });

// --- emit helpers ---

function isParam(f: Field): boolean {
  return f.kind === "param" && !!f.boundTo;
}

// fields that must be present before `call` can run
function needsBootstrap(spec: Spec): Field[] {
  return spec.fields.filter((f) => f.source?.kind === "derived");
}

function bootstrapMethod(spec: Spec): string {
  const derived = needsBootstrap(spec);
  if (derived.length === 0) return "";

  const steps = spec.bootstrap
    .map((step) => {
      const fields = derived.filter((f) => step.provides.includes(f.name));
      const seen = new Set<string>();
      const extracts = fields
        .map((f) => {
          // two fields can resolve to the same cookie or token; emit the
          // extraction once or the client repeats itself
          const src0 = f.source;
          const key =
            src0?.kind === "derived" && src0.via.in === "set-cookie"
              ? `cookie:${src0.via.cookieName}`
              : `field:${f.name}`;
          if (seen.has(key)) return "";
          seen.add(key);

          const src = f.source!;
          if (src.kind !== "derived") return "";
          switch (src.via.in) {
            case "set-cookie":
              return `    this.cookies[${JSON.stringify(src.via.cookieName)}] =
      /${escapeRe(src.via.cookieName)}=([^;]+)/.exec(res.headers.get("set-cookie") ?? "")?.[1] ?? "";`;
            case "header":
              return `    this.session[${JSON.stringify(f.name)}] = res.headers.get(${JSON.stringify(src.via.header)}) ?? "";`;
            case "json":
              return `    this.session[${JSON.stringify(f.name)}] = String(
      (await res.clone().json() as any)${pointerAccess(src.via.pointer)} ?? "");`;
            case "html":
              return `    this.session[${JSON.stringify(f.name)}] =
      /${src.via.pattern}/.exec(await res.clone().text())?.[1] ?? "";`;
          }
        })
        .join("\n");

      return `    const res = await fetch(${JSON.stringify(step.url)}, { method: ${JSON.stringify(step.method)} });
${extracts}`;
    })
    .join("\n\n");

  return `
  // one-time handshake. call before \`call\`; safe to call again to refresh
  async connect(): Promise<void> {
${steps}
  }
`;
}

function guard(spec: Spec): string {
  if (needsBootstrap(spec).length === 0) return "";
  return `    if (Object.keys(this.session).length === 0 && Object.keys(this.cookies).length === 0) {
      await this.connect();
    }
`;
}

function queryLines(spec: Spec): string {
  const lines = spec.fields
    .filter((f) => f.location === "query")
    .map((f) =>
      // optional means the site never sent it — only put it on the url
      // when the caller actually asks for it
      f.optional
        ? `    if (params.${f.boundTo}) url.searchParams.set(${JSON.stringify(f.name)}, params.${f.boundTo});`
        : `    url.searchParams.set(${JSON.stringify(f.name)}, ${valueExpr(f)});`,
    );
  return lines.join("\n");
}

function headerLines(spec: Spec): string {
  const lines = spec.fields
    .filter((f) => f.location === "header")
    .map((f) => `        ${JSON.stringify(f.name)}: ${valueExpr(f)},`);

  if (spec.fields.some((f) => f.location === "cookie")) {
    lines.push(`        cookie: this.cookieHeader(),`);
  }
  return lines.join("\n");
}

function bodyLine(spec: Spec): string {
  const bodyFields = spec.fields.filter((f) => f.location === "body");
  if (bodyFields.length === 0) return "";

  const entries = bodyFields
    .map((f) => `        ${JSON.stringify(f.name)}: ${valueExpr(f)},`)
    .join("\n");

  // encode the body the way the site expects. the captured content-type is
  // the authority — sending JSON to a form endpoint fails in ways that look
  // like an auth problem and waste an hour
  const contentType =
    spec.fields.find(
      (f) => f.location === "header" && f.name.toLowerCase() === "content-type",
    )?.samples[0] ?? "application/json";

  if (/x-www-form-urlencoded/i.test(contentType)) {
    return `\n      body: new URLSearchParams({\n${entries}\n      }).toString(),`;
  }

  return `\n      body: JSON.stringify({\n${entries}\n      }),`;
}

// how a single field's value is produced at call time
function valueExpr(field: Field): string {
  if (field.kind === "param") return `params.${field.boundTo}`;
  if (field.kind === "static") return JSON.stringify(field.samples[0] ?? "");

  const src = field.source;
  if (src?.kind === "timestamp") {
    return src.unit === "ms" ? "String(Date.now())" : "String(Math.floor(Date.now() / 1000))";
  }
  if (src?.kind === "derived") {
    return `this.session[${JSON.stringify(field.name)}] ?? ""`;
  }

  // unresolved: send what we captured. it will work until it expires, and the
  // verifier will say so loudly when it stops working
  return JSON.stringify(field.samples[0] ?? "");
}

function pointerAccess(pointer: string): string {
  return pointer
    .split(".")
    .map((part) => {
      const m = /^([^[]*)((\[\d+\])*)$/.exec(part);
      const key = m?.[1] ? `[${JSON.stringify(m[1])}]` : "";
      return key + (m?.[2] ?? "");
    })
    .join("");
}

function escapeRe(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function pascal(s: string) {
  return s.replace(/(^|[-_ ])(\w)/g, (_, __, c) => c.toUpperCase());
}

// not everything returns json. a login answers with a redirect and no body,
// so .json() would just throw
function readResponse(spec: Spec): string {
  const type = spec.responseSchema.type;

  if (type === "null") {
    // the work was the side effect: a session, a redirect. report the outcome
    return "({ status: res.status, ok: res.ok } as unknown)";
  }

  if (type === "string") return "(await res.text())";

  return "(await res.json())";
}

// --- html client ---
//
// no endpoint existed, so this one fetches the page and pulls the data out of
// it. it needs a parser, which the api clients don't — that's the cost of
// there being no api to find.
async function writeHtmlClient(spec: Spec, name: string) {
  const e = spec.extraction!;
  const args = [
    ...new Set(
      spec.fields.filter((f) => f.kind === "param" && f.boundTo).map((f) => f.boundTo!),
    ),
  ];
  const rowType = Object.keys(e.fields)
    .map((k) => `  ${k}: string;`)
    .join("\n");
  const picks = Object.entries(e.fields)
    .map(([k, sel]) => `      ${JSON.stringify(k)}: pick(node, ${JSON.stringify(sel)}),`)
    .join("\n");

  const code = [
    `// generated by beeline from ${spec.meta.runs} recorded runs.`,
    `// GET ${spec.target.urlTemplate}`,
    `// ${spec.meta.generatedAt}`,
    `//`,
    `// this site has no api — the data is rendered straight into the page. so`,
    `// this fetches the html and extracts ${e.item} (${e.found} of them when we`,
    `// looked). more brittle than an endpoint: restyle the page and this breaks.`,
    `//`,
    "// do not edit: re-run `npm run synth -- " + spec.flow + "` instead.",
    ``,
    `import { parse } from "node-html-parser";`,
    ``,
    `export interface ${name}Row {`,
    rowType,
    `}`,
    ``,
    ...(args.length
      ? [`export interface ${name}Params {`, ...args.map((a) => `  ${a}?: string;`), `}`, ``]
      : []),
    `export class ${name}Client {`,
    args.length
      ? `  async call(params: ${name}Params = {}): Promise<${name}Row[]> {`
      : `  async call(): Promise<${name}Row[]> {`,
    `    const url = new URL(${JSON.stringify(spec.target.urlTemplate)});`,
    // the page narrows itself before rendering, so the argument goes on the url
    ...spec.fields
      .filter((f) => f.location === "query" && f.kind === "param")
      .map(
        (f) =>
          `    if (params.${f.boundTo}) url.searchParams.set(${JSON.stringify(f.name)}, params.${f.boundTo});`,
      ),
    `    const res = await fetch(url);`,
    "    if (!res.ok) throw new Error(`" + spec.flow + ": ${res.status} ${res.statusText}`);",
    ``,
    `    const root = parse(await res.text());`,
    `    return root.querySelectorAll(${JSON.stringify(e.item)}).map((node) => ({`,
    picks,
    `    }));`,
    `  }`,
    `}`,
    ``,
    `function pick(node: any, selector: string): string {`,
    `  // "p@2" means the third <p> anywhere inside the row — css can't say that`,
    `  // when the tags sit under different parents, which here they do`,
    `  const at = /^(.+)@(\\d+)$/.exec(selector);`,
    `  const target = selector === "."`,
    `    ? node`,
    `    : at`,
    `      ? node.querySelectorAll(at[1]!.trim())[Number(at[2])]`,
    `      : node.querySelector(selector);`,
    `  return target?.text.trim().replace(/\\s+/g, " ") ?? "";`,
    `}`,
    ``,
  ].join("\n");

  const outPath = join("out", `${spec.flow}.client.ts`);
  await writeFile(outPath, code);

  const lines = code.split("\n").length;
  console.log(`\n  wrote ${outPath}`);
  console.log(
    `  \x1b[33mhtml extraction\x1b[0m · ${Object.keys(e.fields).length} fields · ${e.found} rows`,
  );
  console.log(`  ${lines} lines\n`);
  emit({ type: "client", flow: spec.flow, lines });
}
