/**
 * Synth: compile a Spec into a standalone typed client.
 *
 *   npm run synth -- films
 *
 * The output has no dependencies and no browser. That is the entire point:
 * everything the browser knew is now either frozen into the source or
 * re-derived by the bootstrap step.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Field, Spec } from "../types.js";
import { toTs } from "../analyze/schema.js";

const flowName = process.argv[2];
if (!flowName) {
  console.error("usage: npm run synth -- <flow name>");
  process.exit(1);
}

const spec: Spec = JSON.parse(
  await readFile(join("out", `${flowName}.spec.json`), "utf8"),
);

const name = pascal(spec.flow);
const params = [...new Set(spec.fields.filter(isParam).map((f) => f.boundTo!))];

const code = `// Generated by curlew from ${spec.meta.runs} recorded runs.
// ${spec.target.method} ${spec.target.urlTemplate}
// ${spec.meta.generatedAt}
//
// Do not edit: re-run \`npm run synth -- ${spec.flow}\` instead.

export type ${name}Response = ${toTs(spec.responseSchema)};

export interface ${name}Params {
${params.map((p) => `  ${p}: string;`).join("\n")}
}

export class ${name}Client {
  private session: Record<string, string> = {};
  private cookies: Record<string, string> = {};
${bootstrapMethod(spec)}
  async call(params: ${name}Params): Promise<${name}Response> {
${guard(spec)}
    const url = new URL(${JSON.stringify(spec.target.urlTemplate)});
${queryLines(spec)}
    const res = await fetch(url, {
      method: ${JSON.stringify(spec.target.method)},
      headers: {
${headerLines(spec)}
      },${bodyLine(spec)}
    });

    if (!res.ok) {
      throw new Error(\`${spec.flow}: \${res.status} \${res.statusText}\`);
    }

    return ${readResponse(spec)} as ${name}Response;
  }

  private cookieHeader(): string {
    return Object.entries(this.cookies)
      .map(([k, v]) => \`\${k}=\${v}\`)
      .join("; ");
  }
}
`;

const outPath = join("out", `${spec.flow}.client.ts`);
await writeFile(outPath, code);

const unresolved = spec.unresolved.length;
console.log(`\n  wrote ${outPath}`);
console.log(
  `  ${params.length} param(s) · ${spec.bootstrap.length} bootstrap step(s)` +
    (unresolved ? ` · \x1b[31m${unresolved} field(s) hardcoded from capture\x1b[0m` : ""),
);
console.log(`  ${code.split("\n").length} lines\n`);

// ─────────────────────────────── emit helpers ───────────────────────────────

function isParam(f: Field): boolean {
  return f.kind === "param" && !!f.boundTo;
}

/** Fields that must be present before `call` can run. */
function needsBootstrap(spec: Spec): Field[] {
  return spec.fields.filter((f) => f.source?.kind === "derived");
}

function bootstrapMethod(spec: Spec): string {
  const derived = needsBootstrap(spec);
  if (derived.length === 0) return "";

  const steps = spec.bootstrap
    .map((step) => {
      const fields = derived.filter((f) => step.provides.includes(f.name));
      const extracts = fields
        .map((f) => {
          const src = f.source!;
          if (src.kind !== "derived") return "";
          switch (src.via.in) {
            case "set-cookie":
              return `    this.cookies[${JSON.stringify(src.via.cookieName)}] =
      /${escapeRe(src.via.cookieName)}=([^;]+)/.exec(res.headers.get("set-cookie") ?? "")?.[1] ?? "";`;
            case "header":
              return `    this.session[${JSON.stringify(f.name)}] = res.headers.get(${JSON.stringify(src.via.header)}) ?? "";`;
            case "json":
              return `    this.session[${JSON.stringify(f.name)}] = String(
      (await res.clone().json() as any)${pointerAccess(src.via.pointer)} ?? "");`;
            case "html":
              return `    this.session[${JSON.stringify(f.name)}] =
      /${src.via.pattern}/.exec(await res.clone().text())?.[1] ?? "";`;
          }
        })
        .join("\n");

      return `    const res = await fetch(${JSON.stringify(step.url)}, { method: ${JSON.stringify(step.method)} });
${extracts}`;
    })
    .join("\n\n");

  return `
  /** One-time handshake. Call before \`call\`; safe to call again to refresh. */
  async connect(): Promise<void> {
${steps}
  }
`;
}

function guard(spec: Spec): string {
  if (needsBootstrap(spec).length === 0) return "";
  return `    if (Object.keys(this.session).length === 0 && Object.keys(this.cookies).length === 0) {
      await this.connect();
    }
`;
}

function queryLines(spec: Spec): string {
  const lines = spec.fields
    .filter((f) => f.location === "query")
    .map((f) => `    url.searchParams.set(${JSON.stringify(f.name)}, ${valueExpr(f)});`);
  return lines.join("\n");
}

function headerLines(spec: Spec): string {
  const lines = spec.fields
    .filter((f) => f.location === "header")
    .map((f) => `        ${JSON.stringify(f.name)}: ${valueExpr(f)},`);

  if (spec.fields.some((f) => f.location === "cookie")) {
    lines.push(`        cookie: this.cookieHeader(),`);
  }
  return lines.join("\n");
}

function bodyLine(spec: Spec): string {
  const bodyFields = spec.fields.filter((f) => f.location === "body");
  if (bodyFields.length === 0) return "";

  const entries = bodyFields
    .map((f) => `        ${JSON.stringify(f.name)}: ${valueExpr(f)},`)
    .join("\n");

  // Encode the body the way the site expects. The captured content-type is
  // the authority — sending JSON to a form endpoint fails in ways that look
  // like an auth problem and waste an hour.
  const contentType =
    spec.fields.find(
      (f) => f.location === "header" && f.name.toLowerCase() === "content-type",
    )?.samples[0] ?? "application/json";

  if (/x-www-form-urlencoded/i.test(contentType)) {
    return `\n      body: new URLSearchParams({\n${entries}\n      }).toString(),`;
  }

  return `\n      body: JSON.stringify({\n${entries}\n      }),`;
}

/** How a single field's value is produced at call time. */
function valueExpr(field: Field): string {
  if (field.kind === "param") return `params.${field.boundTo}`;
  if (field.kind === "static") return JSON.stringify(field.samples[0] ?? "");

  const src = field.source;
  if (src?.kind === "timestamp") {
    return src.unit === "ms" ? "String(Date.now())" : "String(Math.floor(Date.now() / 1000))";
  }
  if (src?.kind === "derived") {
    return `this.session[${JSON.stringify(field.name)}] ?? ""`;
  }

  // Unresolved: send what we captured. It will work until it expires, and the
  // verifier will say so loudly when it stops working.
  return JSON.stringify(field.samples[0] ?? "");
}

function pointerAccess(pointer: string): string {
  return pointer
    .split(".")
    .map((part) => {
      const m = /^([^[]*)((\[\d+\])*)$/.exec(part);
      const key = m?.[1] ? `[${JSON.stringify(m[1])}]` : "";
      return key + (m?.[2] ?? "");
    })
    .join("");
}

function escapeRe(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function pascal(s: string) {
  return s.replace(/(^|[-_ ])(\w)/g, (_, __, c) => c.toUpperCase());
}

/**
 * How the client should read the response body.
 *
 * Not every useful endpoint returns JSON. A form post that establishes a
 * session answers with a redirect and no body at all — there the result is
 * the status and the cookies, and calling .json() on it only throws.
 */
function readResponse(spec: Spec): string {
  const type = spec.responseSchema.type;

  if (type === "null") {
    // The work was the side effect: a session, a redirect. Report the outcome.
    return "({ status: res.status, ok: res.ok } as unknown)";
  }

  if (type === "string") return "(await res.text())";

  return "(await res.json())";
}
