// generated by beeline — do not edit, re-run `beeline deploy steam`
//
// GET https://store.steampowered.com/search/results/
// a site with no public api, behind a url that anyone can call.

import { SteamClient } from "../../out/steam.client.js";

const PARAMS = ["term"];

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    // no params? explain what this is instead of throwing
    if (![...url.searchParams.keys()].length) {
      return json({
        api: "steam",
        source: "https://store.steampowered.com",
        params: PARAMS,
        example: `${url.origin}?${PARAMS.map((p) => `${p}=...`).join("&")}`,
        generated: "2026-09-19T19:34:44.676Z",
      });
    }

    const args: Record<string, string> = {};
    for (const p of PARAMS) {
      const v = url.searchParams.get(p);
      if (!v) return json({ error: `missing param: ${p}`, params: PARAMS }, 400);
      args[p] = v;
    }

    try {
      const started = Date.now();
      const client = new SteamClient();
      const data = await client.call(args as never);
      return json({ ms: Date.now() - started, data });
    } catch (err) {
      // the site changed, or it blocked us. say which, don't return junk
      return json({ error: err instanceof Error ? err.message : String(err) }, 502);
    }
  },
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      // it's a public read-only api; let anything call it
      "access-control-allow-origin": "*",
    },
  });
}
