// wrap a generated client in a worker and ship it.
//   beeline deploy steam
//
// this is the step that turns "a file you import" into "a url anyone can curl".

import { mkdir, writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";
import { spawn } from "node:child_process";
import type { Spec } from "../types.js";

const flowName = process.argv[2];
const dryRun = process.argv.includes("--dry-run");

if (!flowName) {
  console.error("usage: beeline deploy <flow> [--dry-run]");
  process.exit(1);
}

const spec: Spec = JSON.parse(
  await readFile(join("out", `${flowName}.spec.json`), "utf8"),
);

const className = pascal(spec.flow) + "Client";
const params = [
  ...new Set(
    spec.fields.filter((f) => f.kind === "param" && f.boundTo).map((f) => f.boundTo!),
  ),
];

const dir = join("workers", flowName);
await mkdir(dir, { recursive: true });

const worker = `// generated by beeline — do not edit, re-run \`beeline deploy ${flowName}\`
//
// ${spec.target.method} ${spec.target.urlTemplate}
// a site with no public api, behind a url that anyone can call.

import { ${className} } from "../../out/${flowName}.client.js";

const PARAMS = ${JSON.stringify(params)};

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    // no params? explain what this is instead of throwing
    if (![...url.searchParams.keys()].length) {
      return json({
        api: ${JSON.stringify(flowName)},
        source: ${JSON.stringify(spec.origin)},
        params: PARAMS,
        example: \`\${url.origin}?\${PARAMS.map((p) => \`\${p}=...\`).join("&")}\`,
        generated: ${JSON.stringify(spec.meta.generatedAt)},
      });
    }

    const args: Record<string, string> = {};
    for (const p of PARAMS) {
      const v = url.searchParams.get(p);
      if (!v) return json({ error: \`missing param: \${p}\`, params: PARAMS }, 400);
      args[p] = v;
    }

    try {
      const started = Date.now();
      const client = new ${className}();
      const data = await client.call(args as never);
      return json({ ms: Date.now() - started, data });
    } catch (err) {
      // the site changed, or it blocked us. say which, don't return junk
      return json({ error: err instanceof Error ? err.message : String(err) }, 502);
    }
  },
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      // it's a public read-only api; let anything call it
      "access-control-allow-origin": "*",
    },
  });
}
`;

const config = {
  name: `beeline-${flowName}`,
  main: "index.ts",
  compatibility_date: "2026-09-01",
  observability: { enabled: true },
};

await writeFile(join(dir, "index.ts"), worker);
await writeFile(join(dir, "wrangler.jsonc"), JSON.stringify(config, null, 2) + "\n");

console.log(`\n  wrote ${join(dir, "index.ts")}`);
console.log(`  params: ${params.join(", ") || "none"}`);

if (dryRun) {
  console.log(`\n  ${dim("--dry-run: not deploying")}\n`);
  process.exit(0);
}

console.log(`\n  deploying...\n`);

const child = spawn("npx", ["wrangler", "deploy"], {
  cwd: dir,
  stdio: "inherit",
  shell: process.platform === "win32",
});

child.on("exit", (code) => {
  if (code === 0) {
    console.log(`\n  try it:  curl "<your worker url>?${params.map((p) => `${p}=...`).join("&")}"\n`);
  }
  process.exit(code ?? 0);
});

function pascal(s: string) {
  return s.replace(/(^|[-_ ])(\w)/g, (_, __, c) => c.toUpperCase());
}
function dim(s: string) {
  return `\x1b[2m${s}\x1b[0m`;
}
